version: '3.7'

services:

  nginx:
    depends_on: 
        - hostone
        - hosttwo
    
    image: nginx:1.13.11
    ports:
      - 127.0.0.1:8040:8040
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf

  witness:
    build: 
      context: "./AkkaSingleton.Witness"
      dockerfile: "Dockerfile"

    hostname: witness
    ports:
      - '5010:5010'
    environment:
      ClusterName: "Cluster"
      NodePort: 5010
      IsHost: "false"
      SeedNodes:0: "witness:5010"
      SeedNodes:1: "hostone:5010"
      SeedNodes:2: "hosttwo:5010"
  hostone:
    build: 
      context: "./AkkaSingleton"
      dockerfile: "Dockerfile"
    ports:
      - '0:5010'
      - '0:8060'
    hostname: hostone
    environment:
      ClusterName: "Cluster"
      NodePort: 5010
      IsHost: "true"
      SeedNodes:1: "witness:5010"
      SeedNodes:0: "hostone:5010"
      SeedNodes:2: "hosttwo:5010"
    restart: on-failure

  hosttwo:
    build: 
      context: "./AkkaSingleton"
      dockerfile: "Dockerfile"
    ports:
      - '0:5010'
      - '0:8060'
    hostname: 'hosttwo'
    environment:
      ClusterName: "Cluster"
      NodePort: 5010
      IsHost: "true"
      SeedNodes:0: "witness:5010"
      SeedNodes:1: "hostone:5010"
      SeedNodes:2: "hosttwo:5010"
    restart: on-failure
